//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHopDong
    {
        public string SoHopDong { get; set; }
        public string MaNguyenTe { get; set; }
        public string SoLuong { get; set; }
    
        public virtual DMNguyenTe DMNguyenTe { get; set; }
        public virtual HopDongVay HopDongVay { get; set; }
    }
}
