//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongVay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDongVay()
        {
            this.ChiTietHopDong = new HashSet<ChiTietHopDong>();
        }
    
        public string SoHopDong { get; set; }
        public Nullable<System.DateTime> NgayLapHopDong { get; set; }
        public string MaChiNhanh { get; set; }
        public string MaKhachHang { get; set; }
        public string MaThoiHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHopDong> ChiTietHopDong { get; set; }
        public virtual DMChiNhanh DMChiNhanh { get; set; }
        public virtual DMKhachHang DMKhachHang { get; set; }
        public virtual ThoiHanVay ThoiHanVay { get; set; }
    }
}
