//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chau.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChauEntities : DbContext
    {
        public ChauEntities()
            : base("name=ChauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHopDong> ChiTietHopDong { get; set; }
        public virtual DbSet<DMChiNhanh> DMChiNhanh { get; set; }
        public virtual DbSet<DMKhachHang> DMKhachHang { get; set; }
        public virtual DbSet<DMNguyenTe> DMNguyenTe { get; set; }
        public virtual DbSet<HopDongVay> HopDongVay { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TyGia> TyGia { get; set; }
        public virtual DbSet<ThoiHanVay> ThoiHanVay { get; set; }
    }
}
